#!/bin/sh

# exit if any subcommand returns a non-zero status
set -e

FILE=$1

sed -i -e "s@config.REACT_APP_BASE_URL@$REACT_APP_BASE_URL@g" $FILE

sed -i -e "s@config.REACT_APP_FIREBASE_API_KEY@$REACT_APP_FIREBASE_API_KEY@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_AUTH_DOMAIN@$REACT_APP_FIREBASE_AUTH_DOMAIN@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_PROJECT_ID@$REACT_APP_FIREBASE_PROJECT_ID@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_STORAGE_BUCKET@$REACT_APP_FIREBASE_STORAGE_BUCKET@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_MESSAGING_SENDER_ID@$REACT_APP_FIREBASE_MESSAGING_SENDER_ID@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_APP_ID@$REACT_APP_FIREBASE_APP_ID@g" $FILE
sed -i -e "s@config.REACT_APP_FIREBASE_MEASUREMENT_ID@$REACT_APP_FIREBASE_MEASUREMENT_ID@g" $FILE