interface typeNotification {
  ORDER_CONVERT_QUOTATION_CUSTOMER: string;
  ORDER_QUOTATION_CUSTOMER: string;
}
export const TYPE_NOTIFICATION : typeNotification= {
  ORDER_CONVERT_QUOTATION_CUSTOMER: "ORDER_CONVERT_QUOTATION_CUSTOMER",
  ORDER_QUOTATION_CUSTOMER: "ORDER_QUOTATION_CUSTOMER",
};