export const TYPE_BENEFIT = {
  KPIS_TDV: "KPIS_TDV",
  KPIS_TEAMLEADER: "KPIS_TEAMLEADER",
  KPIS_ASM: "KPIS_ASM",

  BENEFIT_BASE: "BENEFIT_BASE",
  BENEFIT_TDV: "BENEFIT_TDV",
  BENEFIT_TEAMLEADER: "BENEFIT_TEAMLEADER",
  BENEFIT_ASM: "BENEFIT_ASM",

  BENEFIT_TDV_OVER__QUANTER: "BENEFIT_TDV_OVER__QUANTER",
  BENEFIT_TEAMLEADER_OVER__QUANTER: "BENEFIT_TEAMLEADER_OVER__QUANTER",
  BENEFIT_ASM_OVER__QUANTER: "BENEFIT_ASM_OVER__QUANTER",

  BENEFIT_TDV_OVER__YEAR: "BENEFIT_TDV_OVER__YEAR",
  BENEFIT_TEAMLEADER_OVER__YEAR: "BENEFIT_TEAMLEADER_OVER__YEAR",
  BENEFIT_ASM_OVER__YEAR: "BENEFIT_ASM_OVER__YEAR",

  BENEFIT_TDV_OVER: "BENEFIT_TDV_OVER",
  BENEFIT_TEAMLEADER_OVER: "BENEFIT_TEAMLEADER_OVER",
  BENEFIT_ASM_OVER: "BENEFIT_ASM_OVER",

  BENEFIT_WORKING: "BENEFIT_WORKING",
} as const;

export const GROUP_TYPE_BENEFIT_EMPLOYEE_LEVEL = {
  TDV: [
    TYPE_BENEFIT.BENEFIT_BASE,
    TYPE_BENEFIT.BENEFIT_TDV,
    TYPE_BENEFIT.KPIS_TDV,
    TYPE_BENEFIT.BENEFIT_TDV_OVER,
    TYPE_BENEFIT.BENEFIT_TDV_OVER__QUANTER,
    TYPE_BENEFIT.BENEFIT_TDV_OVER__YEAR,
  ],
  TEAMLEADER: [
    TYPE_BENEFIT.BENEFIT_TEAMLEADER,
    TYPE_BENEFIT.KPIS_TEAMLEADER,
    TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER,
    TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER__QUANTER,
    TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER__YEAR,
  ],
  ASM: [
    TYPE_BENEFIT.BENEFIT_ASM,
    TYPE_BENEFIT.KPIS_ASM,
    TYPE_BENEFIT.BENEFIT_ASM_OVER,
    TYPE_BENEFIT.BENEFIT_ASM_OVER__QUANTER,
    TYPE_BENEFIT.BENEFIT_ASM_OVER__YEAR,
  ],
  BENEFIT_WORKING:[
    TYPE_BENEFIT.BENEFIT_WORKING
  ]
};
export const GROUP_TYPE_BENEFIT_EMPLOYEE_LEVEL_VI = {
    TDV : "Trình dược viên",
    TEAMLEADER : "Trưởng nhóm bán hàng",
    ASM : "Quản lý vùng",
    BENEFIT_WORKING : "Giờ làm việc hiệu quả",
}
export const TYPE_BENEFIT_VI = {
  BENEFIT_TDV: "Hoa hồng TDV",
  BENEFIT_BASE: "Hoa hồng CTV",
  BENEFIT_TEAMLEADER: "Hoa hồng TeamLead",
  BENEFIT_ASM: "Hoa hồng Asm",

  BENEFIT_TDV_OVER__QUANTER: "Hoa hồng TDV Quý",
  BENEFIT_TEAMLEADER_OVER__QUANTER: "Hoa hồng TeamLoad Quý",
  BENEFIT_ASM_OVER__QUANTER: "Hoa hồng Asm Quý",

  BENEFIT_TDV_OVER__YEAR: "Hoa hồng Tdv Năm",
  BENEFIT_TEAMLEADER_OVER__YEAR: "Hoa hồng TeamLead Năm",
  BENEFIT_ASM_OVER__YEAR: "Hoa hồng Asm Năm",

  BENEFIT_TDV_OVER: "Thưởng vượt hoa hồng cho TDV",
  BENEFIT_TEAMLEADER_OVER: "Thưởng vượt hoa hồng cho TeamLead",
  BENEFIT_ASM_OVER: "Thưởng vượt hoa hồng cho Asm",

  KPIS_TDV: "Kpis TDV",
  KPIS_TEAMLEADER: "Kpis TeamLead",
  KPIS_ASM: "Kpis ASM",

  BENEFIT_WORKING: "Giờ làm việc hiệu quả",
} as const;

export const GROUP_TYPE_BENEFIT_BASE: any[] = [
  TYPE_BENEFIT.BENEFIT_BASE,
  TYPE_BENEFIT.BENEFIT_TDV,
];
export const GROUP_TYPE_BENEFIT: any[] = [
  TYPE_BENEFIT.BENEFIT_TEAMLEADER,
  TYPE_BENEFIT.BENEFIT_ASM,
];
export const GROUP_TYPE_BENEFIT_KPIS: any[] = [
  TYPE_BENEFIT.KPIS_TDV,
  TYPE_BENEFIT.KPIS_TEAMLEADER,
  TYPE_BENEFIT.KPIS_ASM,
];

export const GROUP_TYPE_BENEFIT_OVER_QUARTER: any[] = [
  TYPE_BENEFIT.BENEFIT_TDV_OVER__QUANTER,
  TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER__QUANTER,
  TYPE_BENEFIT.BENEFIT_ASM_OVER__QUANTER,
];
export const GROUP_TYPE_BENEFIT_OVER_YEAR: any[] = [
  TYPE_BENEFIT.BENEFIT_TDV_OVER__YEAR,
  TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER__YEAR,
  TYPE_BENEFIT.BENEFIT_ASM_OVER__YEAR,
];
export const GROUP_TYPE_BENEFIT_OVER_MONTH: any[] = [
  TYPE_BENEFIT.BENEFIT_TDV_OVER,
  TYPE_BENEFIT.BENEFIT_TEAMLEADER_OVER,
  TYPE_BENEFIT.BENEFIT_ASM_OVER,
];

export const GROUP_TYPE_BENEFIT_OVER: any[] = [
  ...GROUP_TYPE_BENEFIT_OVER_QUARTER,
  ...GROUP_TYPE_BENEFIT_OVER_YEAR,
  ...GROUP_TYPE_BENEFIT_OVER_MONTH,
];

export const TYPE_KPI = {
  COVER_POS: "COVER_POS",
  EXCLUSIVE_PRODUCT: "EXCLUSIVE_PRODUCT",
  IDEA: "IDEA",
} as const;

export const TYPE_KPI_VI = {
  COVER_POS: "Độ phủ thị trường",
  EXCLUSIVE_PRODUCT: "SP độc quyền",
  IDEA: "Ý kiến đóng góp",
};
