const policyRule = {
  READ_STAFF: "READ_STAFF",
  WRITE_STAFF: "WRITE_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  DELETE_STAFF: "DELETE_STAFF",
  DOWNLOAD_STAFF: "DOWNLOAD_STAFF",
  //
  READ_STAFFGROUP: "READ_STAFFGROUP",
  WRITE_STAFFGROUP: "WRITE_STAFFGROUP",
  UPDATE_STAFFGROUP: "UPDATE_STAFFGROUP",
  DELETE_STAFFGROUP: "DELETE_STAFFGROUP",
  DOWNLOAD_STAFFGROUP: "DOWNLOAD_STAFFGROUP",
} as const;

export type PoliciesRuleType = keyof typeof policyRule
